USE [project3]
GO

/****** Object:  Table [dbo].[Excercise]    Script Date: 02-11-2020 17:04:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Excercise](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[description] [varchar](1000) NULL,
 CONSTRAINT [PK_Excercise] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


